export enum WagerTransactionKind {
  OPENING = 'OPENING',
  BET = 'BET',
  WIN = 'WIN',
  LOSS = 'LOSS',
  REFUND = 'REFUND',
  ROLLBACK = 'ROLLBACK',
}

export enum WagerTransactionStatus {
  PENDING = 'PENDING',
  PENDING_REFERENCE = 'PENDING_REFERENCE',
  PROCESSED = 'PROCESSED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}


export enum FailureCode {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  REVERSAL_INSUFFICIENT_BALANCE = 'REVERSAL_INSUFFICIENT_BALANCE',
  REFERENCE_NOT_FOUND = 'REFERENCE_NOT_FOUND',
  REFERENCE_ALREADY_REVERSED = 'REFERENCE_ALREADY_REVERSED',
  REFERENCE_INCORRECT_AMOUNT = 'REFERENCE_INCORRECT_AMOUNT',
  REFERENCE_INCORRECT_PLAYER = 'REFERENCE_INCORRECT_PLAYER',
  REFERENCE_INCORRECT_WALLET = 'REFERENCE_INCORRECT_WALLET',
  REFERENCE_INCORRECT_CURRENCY = 'REFERENCE_INCORRECT_CURRENCY',
  REFERENCE_INCORRECT_ROUND = 'REFERENCE_INCORRECT_ROUND',
  REFERENCE_INCORRECT_PROVIDER = 'REFERENCE_INCORRECT_PROVIDER',
  REFERENCE_INCORRECT_KIND = 'REFERENCE_INCORRECT_KIND',
  REFERENCE_NOT_TERMINAL = 'REFERENCE_NOT_TERMINAL',
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  CURRENCY_MISMATCH = 'CURRENCY_MISMATCH',
  NEGATIVE_AMOUNT = 'NEGATIVE_AMOUNT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export enum LedgerDirection {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}
